global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'tariff-service'
    static_configs:
      - targets: ['ispark_otopark-tariff-service-1:8080']
    metrics_path: '/actuator/prometheus'