global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'tariff-service'
    static_configs:
      - targets: ['tariff-service:8080:8080']
    metrics_path: '/actuator/prometheus'
  - job_name: 'tariff-service'
    static_configs:
      - targets: ['vehicle-type-service:8081:8080']
    metrics_path: '/actuator/prometheus'
  - job_name: 'vehicle-type-service'

