spring.application.name=api-gateway-service

spring.redis.host=redis-service  # Redis servisinin hostname'i veya IP adresi
spring.redis.port=6379           # Redis'in çalıştığı port
  
  # Gateway route for tariff-service
spring.cloud.gateway.routes[0].id=tariff-service
spring.cloud.gateway.routes[0].uri=http://tariff-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/tariffs/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/v1/tariffs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=20
  
  # Gateway route for vehicle-type-service
spring.cloud.gateway.routes[1].id=vehicle-type-service
spring.cloud.gateway.routes[1].uri=http://vehicle-type-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vehicle-types/**
  
  # Gateway route for customer-type-service
spring.cloud.gateway.routes[2].id=customer-type-service
spring.cloud.gateway.routes[2].uri=http://customer-type-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/customer-types/**
spring.cloud.gateway.routes[2].predicates[1]=Method=GET

server.port=8084

management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.export.prometheus.enabled=true

logging.level.org.springframework=INFO
logging.level.com.ispark=DEBUG
